name: Release

on: 
  push:
    branches:
      - 'release/**'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake g++ make libgtest-dev libgmock-dev

    - name: Get Version
      uses: battila7/get-version-action@v2.2.1

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON -DVERSION_MAJOR=${{ steps.get_version.outputs.major }} -DVERSION_MINOR=${{ steps.get_version.outputs.minor }} -DVERSION_PATCH=${{ steps.get_version.outputs.patch }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Create package
      working-directory: ${{ github.workspace }}/build
      run: cpack -C ${{env.BUILD_TYPE}}

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/hello_actions-${{ steps.get_version.outputs.version }}-Linux.deb
        asset_name: hello_actions-${{ steps.get_version.outputs.version }}-Linux.deb
        asset_content_type: application/vnd.debian.binary-package

